import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Popug Corp | SSO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="center-screen">
        <h1>SSO Home page</h1>

        <div>
          <a href="/sign-in" className="btn btn-primary">
            Sign In
          </a>
        </div>
      </main>
    </>
  );
};

export default Home;
